
title: "Nikolay Nikolov"
subtitle: "nikonikolov"
description: > # this means to ignore newlines until "baseurl:"
  Nikolay Nikolov personal website

baseurl: ""
# baseurl: "/" # the subpath of your site, e.g. /blog
url: http://nikonikolov

email: "niko [dot] b [dot] nikolov [at] gmail [dot] com"
linkedin: "nikobnikolov"
github: "nikonikolov"
google-scholar: "https://scholar.google.com/citations?hl=en&authuser=3&user=UvNjyt8AAAAJ"

# Exclude these when building _site
exclude: [Notes.txt, README.md, resources, UPDATES]
